//! Theme colors for the visualizer.
//!
//! Priority:
//!   1. `--theme FILE` flag
//!   2. `~/.config/tacos-lyrics/theme.txt`
//!   3. Terminal palette defaults (always follow the terminal colorscheme)
//!
//! A theme file is plain text: `key = value` lines, `#` comments.
//! Values: `#rrggbb`, `palette:N` (0-255, follows terminal theme),
//! `default` (terminal foreground), `dim` (faint foreground).
//!
//! The file can be generated by theming tools (noctalia, matugen...) and
//! the visualizer reloads it on SIGUSR1 - see templates/ in the repo.

use std::path::{Path, PathBuf};

/// One color, resolved to an ANSI SGR sequence when rendered.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorSpec {
    /// Explicit `#rrggbb` -> truecolor SGR
    Hex(u8, u8, u8),
    /// 256-color palette slot -> `38;5;N`, follows the terminal theme
    Palette(u8),
    /// Terminal default foreground -> SGR 39
    Default,
    /// Faint terminal foreground -> SGR 2;39
    Faint,
}

impl ColorSpec {
    /// The SGR escape sequence that selects this color.
    pub fn sgr(&self) -> String {
        match self {
            ColorSpec::Hex(r, g, b) => format!("\x1b[38;2;{};{};{}m", r, g, b),
            ColorSpec::Palette(n) => format!("\x1b[38;5;{}m", n),
            ColorSpec::Default => "\x1b[39m".to_string(),
            ColorSpec::Faint => "\x1b[2;39m".to_string(),
        }
    }

    /// Parse a value from a theme file. Returns None for junk.
    pub fn parse(raw: &str) -> Option<Self> {
        let s = raw.trim();
        if s.is_empty() {
            return None;
        }
        if let Some(hex) = s.strip_prefix('#') {
            let hex = hex.trim();
            return match hex.len() {
                3 => {
                    let r = u8::from_str_radix(&hex[0..1].repeat(2), 16).ok()?;
                    let g = u8::from_str_radix(&hex[1..2].repeat(2), 16).ok()?;
                    let b = u8::from_str_radix(&hex[2..3].repeat(2), 16).ok()?;
                    Some(ColorSpec::Hex(r, g, b))
                }
                6 => {
                    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
                    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
                    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
                    Some(ColorSpec::Hex(r, g, b))
                }
                _ => None,
            };
        }
        let lower = s.to_ascii_lowercase();
        match lower.as_str() {
            "default" | "fg" | "normal" => Some(ColorSpec::Default),
            "dim" | "faint" => Some(ColorSpec::Faint),
            _ => {
                // palette:N / index:N / pN / p:N
                let num = lower
                    .strip_prefix("palette:")
                    .or_else(|| lower.strip_prefix("index:"))
                    .or_else(|| lower.strip_prefix("p:"))
                    .or_else(|| lower.strip_prefix('p'))
                    .map(str::trim);
                let n: u8 = num?.parse().ok()?;
                Some(ColorSpec::Palette(n))
            }
        }
    }
}

/// The four colors the visualizer uses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Theme {
    /// karaoke: the words already sung (or the whole line if no karaoke)
    pub sung: ColorSpec,
    /// karaoke: the words not yet sung
    pub unsung: ColorSpec,
    /// the whole line while playback is paused
    pub paused: ColorSpec,
    /// the "artist - title" header line
    pub header: ColorSpec,
}

impl Theme {
    /// Default theme: palette-index colors, so the lyrics always follow
    /// the terminal's own colorscheme (foot, kitty, alacritty, ... all
    /// remap these slots when the theme changes - even live).
    pub fn terminal() -> Self {
        Theme {
            sung: ColorSpec::Default,      // terminal foreground
            unsung: ColorSpec::Palette(8), // "bright black" = theme gray
            paused: ColorSpec::Palette(8),
            header: ColorSpec::Palette(8),
        }
    }

    /// Default theme-file location: ~/.config/tacos-lyrics/theme.txt
    pub fn config_path() -> PathBuf {
        let base = std::env::var_os("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| {
                PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".config")
            });
        base.join("tacos-lyrics").join("theme.txt")
    }

    /// Load a theme file. Missing/invalid keys keep the terminal defaults;
    /// returns None only if the file can't be read at all.
    pub fn from_file(path: &Path) -> Option<Self> {
        let text = std::fs::read_to_string(path).ok()?;
        let mut theme = Theme::terminal();
        let mut saw_any = false;
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                continue;
            };
            let key = key.trim().to_ascii_lowercase();
            let Some(spec) = ColorSpec::parse(value) else {
                continue;
            };
            saw_any = true;
            match key.as_str() {
                "sung" => theme.sung = spec,
                "unsung" | "dim" => theme.unsung = spec,
                "paused" => theme.paused = spec,
                "header" => theme.header = spec,
                _ => {} // unknown keys are ignored (forward compatible)
            }
        }
        if saw_any {
            Some(theme)
        } else {
            None // file existed but had nothing usable
        }
    }

    /// Load from an explicit flag path, or the config path, or terminal
    /// defaults. This is the single entry point used by the main loop,
    /// including on SIGUSR1 reloads.
    pub fn load(explicit: Option<&Path>) -> Theme {
        if let Some(p) = explicit {
            return Theme::from_file(p).unwrap_or_else(Theme::terminal);
        }
        let p = Theme::config_path();
        if p.is_file() {
            Theme::from_file(&p).unwrap_or_else(Theme::terminal)
        } else {
            Theme::terminal()
        }
    }
}

#[cfg(test)]
impl Theme {
    pub fn sgr_sung(&self) -> String {
        self.sung.sgr()
    }
    pub fn sgr_unsung(&self) -> String {
        self.unsung.sgr()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_hex() {
        assert_eq!(
            ColorSpec::parse("#cba6f7"),
            Some(ColorSpec::Hex(0xcb, 0xa6, 0xf7))
        );
        assert_eq!(
            ColorSpec::parse("#fff"),
            Some(ColorSpec::Hex(255, 255, 255))
        );
        assert_eq!(ColorSpec::parse("#1234"), None);
        assert_eq!(ColorSpec::parse("#zzzzzz"), None);
    }

    #[test]
    fn parse_named() {
        assert_eq!(ColorSpec::parse("default"), Some(ColorSpec::Default));
        assert_eq!(ColorSpec::parse("FG"), Some(ColorSpec::Default));
        assert_eq!(ColorSpec::parse("dim"), Some(ColorSpec::Faint));
        assert_eq!(ColorSpec::parse("faint"), Some(ColorSpec::Faint));
        assert_eq!(ColorSpec::parse("palette:8"), Some(ColorSpec::Palette(8)));
        assert_eq!(ColorSpec::parse("p:3"), Some(ColorSpec::Palette(3)));
        assert_eq!(ColorSpec::parse("palette:256"), None);
        assert_eq!(ColorSpec::parse("junk"), None);
        assert_eq!(ColorSpec::parse(""), None);
    }

    #[test]
    fn sgr_sequences() {
        assert_eq!(ColorSpec::Hex(1, 2, 3).sgr(), "\x1b[38;2;1;2;3m");
        assert_eq!(ColorSpec::Palette(8).sgr(), "\x1b[38;5;8m");
        assert_eq!(ColorSpec::Default.sgr(), "\x1b[39m");
        assert_eq!(ColorSpec::Faint.sgr(), "\x1b[2;39m");
    }

    #[test]
    fn theme_from_file() {
        let dir = std::env::temp_dir().join("tcl_theme_test");
        std::fs::create_dir_all(&dir).unwrap();
        let f = dir.join("t.txt");
        std::fs::write(
            &f,
            "# comment\n\nsung   = #ff0000\nunsung = palette:8\npaused = dim\nheader = default\nbogus  = nope\nunknown_key = #111111\n",
        )
        .unwrap();
        let t = Theme::from_file(&f).unwrap();
        assert_eq!(t.sung, ColorSpec::Hex(255, 0, 0));
        assert_eq!(t.unsung, ColorSpec::Palette(8));
        assert_eq!(t.paused, ColorSpec::Faint);
        assert_eq!(t.header, ColorSpec::Default);
    }

    #[test]
    fn theme_file_partial_keeps_defaults() {
        let dir = std::env::temp_dir().join("tcl_theme_test");
        std::fs::create_dir_all(&dir).unwrap();
        let f = dir.join("partial.txt");
        std::fs::write(&f, "sung = #00ff00\n").unwrap();
        let t = Theme::from_file(&f).unwrap();
        assert_eq!(t.sung, ColorSpec::Hex(0, 255, 0));
        assert_eq!(t.unsung, Theme::terminal().unsung); // kept
        assert_eq!(t.header, Theme::terminal().header); // kept
    }

    #[test]
    fn empty_theme_file_is_none() {
        let dir = std::env::temp_dir().join("tcl_theme_test");
        std::fs::create_dir_all(&dir).unwrap();
        let f = dir.join("empty.txt");
        std::fs::write(&f, "# only comments\n").unwrap();
        assert!(Theme::from_file(&f).is_none());
    }

    #[test]
    fn missing_file_is_none() {
        assert!(Theme::from_file(Path::new("/nonexistent/nope.txt")).is_none());
    }

    #[test]
    fn terminal_default_uses_palette() {
        let t = Theme::terminal();
        assert_eq!(t.sgr_sung(), "\x1b[39m");
        assert_eq!(t.sgr_unsung(), "\x1b[38;5;8m");
    }
}
